apiVersion: skaffold/v4beta10
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticketing-dev-422708/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ticketing-dev-422708
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}